services:
  app:
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME}
        USER_EMAIL: ${USER_EMAIL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true